export const DifficultyLevels = () => ({
    newbie: {
        gridWidth: 2,
        slideWidth: 4,
        tilesPerPatrol: 5,
        rockChance: 0,
        tilesX: 6,
        tilesY: 6,
    },
    easy: {
        gridWidth: 2,
        slideWidth: 3,
        tilesPerPatrol: 4,
        rockChance: 5,
        tilesX: 6,
        tilesY: 6,
    },
    normal: {
        gridWidth: 2,
        slideWidth: 2,
        tilesPerPatrol: 3,
        rockChance: 5,
        tilesX: 6,
        tilesY: 6,
    },
    hard: {
        gridWidth: 2,
        slideWidth: 2,
        tilesPerPatrol: 2,
        rockChance: 5,
        tilesX: 7,
        tilesY: 7,
    },
    insane: {
        gridWidth: 2,
        slideWidth: 2,
        tilesPerPatrol: 1,
        rockChance: 5,
        tilesX: 8,
        tilesY: 8,
    },
})
